### ISSUE TITLE
ログイン機能実装

### ISSUE THREAD

**Issue by ShiraiYuya** [ShiraiYuya/SystemX#2]
## 概要
ログイン画面の作成ならびに認証機能の実装
※プロトタイプ段階ではユーザ情報は予めDBに登録しておく
※全ユーザが全機能にアクセスする権限を持つ

## 詳細
-  [ ] ログイン画面と入力フォームの作成
-  [ ] ユーザ管理DBの作成、ユーザ情報の登録
-  [ ] ユーザ認証機能の実装
-  [ ] セッション内でのユーザ情報保持を実現
-  [ ] ログアウトボタンをヘッダに実装

**Comment by yojimasentaro** [comment]
ユーザ認証に関しては、deviseというgemあるいはcancancanを使用すると良いです（管理権限をあまり変えなくていいならdeviseをオススメします）
