### ISSUE TITLE
指示書出力機能

### ISSUE THREAD

**Issue by ShiraiYuya** [ShiraiYuya/SystemX#3]
## 概要
その日の出荷量データをCSVで受け取り、 #4 （機械学習）の出力結果ならびに在庫情報と連携して各種指示書を出力

## 詳細
-  [ ] CSVファイルの入力フォーマット作成
-  [ ] CSVファイルのデータ取得
-  [ ] 取得データを #4 側に送信
-  [ ] #4 の出力結果、CSVのデータ、在庫情報から指示書出力
    -  [ ] 仕込み作業指示書
    -  [ ] 製造指示書
    -  [ ] 梱包指示書
    -  [ ] 全体管理用台帳

**Comment by yojimasentaro** [comment]
これについてはもうちょっと話した方が良いかも
（基幹システムにcsv出力があるので、我々はつくりおき分に関してのみの指示書を作成するのでもいいかもしれない？）

合計して出力してあげる機能は魅力的だけど、最初からcsvを書く機能を作らないといけないならコストに見合わないと感じる。。
